[tool.black]
line-length = 88
target-version = ["py312"]
exclude = '(/\.venv/|/build/|/dist/)'

[tool.ruff]
line-length = 88
exclude = [".venv", "build", "dist"]
target-version = "py312"
fix = true

[tool.ruff.lint]
select = ["E","F","I","UP","B","SIM","PL","RUF"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true
